// 创建模拟数据
export const dataSource1 = [
    {
        key:'0',
        title:'0',
        children:[
            {
                key:'0-1',
                title:'0-1',
            },
            {
                key:'0-2',
                title:'0-2',
            }
        ]
    },
    {
        key:'1',
        title:'1',
        children:[
            {
                key:'1-1',
                title:'1-1',
            },
            {
                key:'1-2',
                title:'1-2',
            }
        ]
    },
    {
        key:'2',
        title:'2'
    },
    {
        key:'3',
        title:'3',
        children:[
            {
                key:'3-1',
                title:'3-1',
            },
            {
                key:'3-2',
                title:'3-2',
            }
        ]
    }
];

export const dataSource2 = [
    {
        key:'4',
        title:'4',
        children:[
            {
                key:'4-1',
                title:'4-1',
            },
            {
                key:'4-2',
                title:'4-2',
            }
        ]
    },
    {
        key:'5',
        title:'5',
        children:[
            {
                key:'5-1',
                title:'5-1',
            },
            {
                key:'5-2',
                title:'5-2',
            }
        ]
    },
    {
        key:'6',
        title:'6'
    },
    {
        key:'7',
        title:'7',
        children:[
            {
                key:'7-1',
                title:'7-1',
            },
            {
                key:'7-2',
                title:'7-2'
            }
        ]
    }
];


